# Generated by Django 3.2.12 on 2022-03-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostra',
            new_name='mostrar',
        ),
    ]
