# Generated by Django 3.2.12 on 2022-03-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contato_id_dono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='id_dono',
            new_name='dono',
        ),
    ]
